notebook/book/python/Test-Driven-Development-With-Python/superlists/lists/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^(\d+)/$', 'lists.views.view_list', name='view_list'),
    url(r'^(\d+)/add_item$', 'lists.views.add_item', name='add_item'),
    url(r'^new$', 'lists.views.new_list', name='new_list'),
]

notebook/book/python/Test-Driven-Development-With-Python/superlists/superlists/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'lists.views.home_page', name='home'),
    url(r'^lists/', include('lists.urls')),
]

notebook/book/python/Test-Driven-Development-With-Python/superlists/lists/models.py
from django.db import models


class List(models.Model):
    pass


# Create your models here.
class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

notebook/book/python/Test-Driven-Development-With-Python/superlists/lists/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from lists.models import Item, List


# Create your views here.
def home_page(request):
    return render(request, 'home.html')


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    items = Item.objects.filter(list=list_)
    return render(request, 'list.html', {'list': list_})


def new_list(request):
    list_ = List.objects.create()
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect('/lists/%d/' % (list_.id,))


def add_item(request, list_id):
    list_ = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect('/lists/%d/' % (list_.id,))

notebook/book/python/Test-Driven-Development-With-Python/superlists/lists/templates/home.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>To-Do lists</title>
    </head>
    <body>
        <h1>Your To-Do list</h1>
        <form method="post" action="/lists/new">
            {% csrf_token %}
            <input type="text" name="item_text" id="id_new_item" placeholder="Enter a to-do item" value="">
        </form>
    </body>
</html>

notebook/book/python/Test-Driven-Development-With-Python/superlists/lists/templates/list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>To-Do lists</title>
    </head>
    <body>
        <h1>Your To-Do list</h1>
        <form method="post" action="/lists/{{ list.id }}/add_item">
            {% csrf_token %}
            <input type="text" name="item_text" id="id_new_item" placeholder="Enter a to-do item" value="">
        </form>
        <table id="id_list_table">
            {% for item in list.item_set.all %}
            <tr>
                <td>
                    {{ forloop.counter }}: {{ item.text }}
                </td>
            </tr>
            {% endfor %}
        </table>
    </body>
</html>